# Generated by Django 6.1.1 on 2026-09-22 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_cambiar_password', models.BooleanField(default=False, help_text='Obliga a cambiar la clave antes de usar el panel.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_operador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de operador',
                'verbose_name_plural': 'perfiles de operador',
            },
        ),
    ]
