-- ============================================================================
-- Esquema `empleo`: datos del bot de postulacion, alojado en el proyecto SurIA.
--
-- Las tablas viven en un esquema propio, cerrado: ni anon ni authenticated
-- pueden tocarlas directamente. Todo acceso pasa por las funciones
-- public.empleo_*, que exigen una sesion de Supabase Auth cuyo usuario este en
-- empleo.operators. Asi el esquema no necesita estar expuesto por la API y no
-- se toca la configuracion de esquemas expuestos que usan las otras apps.
-- ============================================================================

create schema if not exists empleo;
revoke all on schema empleo from public, anon, authenticated;

-- ----------------------------------------------------------------- tablas

create table empleo.operators (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table empleo.companies (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  website    text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table empleo.jobs (
  id             bigint generated by default as identity primary key,
  company_id     bigint references empleo.companies (id) on delete set null,
  platform       text not null default 'Magneto365',
  title          text not null,
  company_name   text not null,
  salary         text,
  location       text,
  modality       text,
  published_at   text,
  url            text not null unique,
  description    text,
  match_score    integer not null default 0,
  priority       text not null default 'normal' check (priority in ('baja', 'normal', 'alta')),
  recommendation text,
  status         text not null default 'found'
                 check (status in ('found', 'discarded', 'applied', 'error', 'no_available')),
  first_seen_at  timestamptz not null default now(),
  last_seen_at   timestamptz not null default now(),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index jobs_match_score_idx on empleo.jobs (match_score);
create index jobs_status_idx on empleo.jobs (status);
create index jobs_company_idx on empleo.jobs (company_id);

create table empleo.applications (
  id         bigint generated by default as identity primary key,
  job_id     bigint not null unique references empleo.jobs (id) on delete cascade,
  applied_at timestamptz not null default now(),
  status     text not null check (status in ('applied', 'error', 'no_available', 'skipped')),
  response   text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table empleo.skills (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  created_at timestamptz not null default now()
);

create table empleo.job_skills (
  job_id   bigint not null references empleo.jobs (id) on delete cascade,
  skill_id bigint not null references empleo.skills (id) on delete cascade,
  primary key (job_id, skill_id)
);
create index job_skills_skill_idx on empleo.job_skills (skill_id);

create table empleo.questions (
  id               bigint generated by default as identity primary key,
  job_id           bigint references empleo.jobs (id) on delete set null,
  question_text    text not null,
  answer_given     text not null,
  confidence_score numeric(3, 2) not null,
  created_at       timestamptz not null default now()
);
create index questions_created_at_idx on empleo.questions (created_at);
create index questions_job_idx on empleo.questions (job_id);

-- Cada clic en "Ejecutar" del panel es una fila. El agente de la PC la toma,
-- lanza el bot y va dejando aqui el estado y la cola del log.
create table empleo.bot_runs (
  id           bigint generated by default as identity primary key,
  requested_by uuid references auth.users (id) on delete set null,
  max_offers   integer not null check (max_offers between 1 and 50),
  status       text not null default 'pending'
               check (status in ('pending', 'running', 'finished', 'failed', 'cancelled', 'expired')),
  machine      text,
  requested_at timestamptz not null default now(),
  started_at   timestamptz,
  finished_at  timestamptz,
  exit_code    integer,
  log_tail     text,
  summary      jsonb
);
create index bot_runs_status_idx on empleo.bot_runs (status, requested_at);
create index bot_runs_requested_by_idx on empleo.bot_runs (requested_by);

-- Latido del agente: el panel sabe si la PC esta prendida y escuchando.
create table empleo.agents (
  machine      text primary key,
  last_seen_at timestamptz not null default now(),
  browser_ok   boolean not null default false
);

-- RLS activo y sin politicas: nadie entra por la API directa, solo por las
-- funciones de abajo (security definer).
alter table empleo.operators    enable row level security;
alter table empleo.companies    enable row level security;
alter table empleo.jobs         enable row level security;
alter table empleo.applications enable row level security;
alter table empleo.skills       enable row level security;
alter table empleo.job_skills   enable row level security;
alter table empleo.questions    enable row level security;
alter table empleo.bot_runs     enable row level security;
alter table empleo.agents       enable row level security;

-- ------------------------------------------------------------ autorizacion

create function empleo.exigir_operador() returns void
language plpgsql stable security definer set search_path = '' as $$
begin
  if not exists (select 1 from empleo.operators o where o.user_id = (select auth.uid())) then
    raise exception 'No autorizado' using errcode = '42501';
  end if;
end $$;

-- Plazos que el agente y el panel comparten. Viven en un solo lugar.
create function empleo.segundos_agente_en_linea() returns integer
language sql immutable set search_path = '' as $$ select 45 $$;

create function empleo.minutos_vigencia_solicitud() returns integer
language sql immutable set search_path = '' as $$ select 30 $$;

-- ------------------------------------------------------------ panel (lectura)

create function public.empleo_es_operador() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from empleo.operators o where o.user_id = (select auth.uid()));
$$;

create function public.empleo_resumen(p_umbral integer default 45) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return (
    select jsonb_build_object(
      'total',        count(*),
      'aplicadas',    count(*) filter (where j.status = 'applied'),
      'descartadas',  count(*) filter (where j.status = 'discarded'),
      'pendientes',   count(*) filter (where j.status = 'found'),
      'conError',     count(*) filter (where j.status in ('error', 'no_available')),
      'calificadas',  count(*) filter (where j.match_score >= p_umbral),
      'promedio',     coalesce(round(avg(j.match_score)), 0),
      'preguntas',    (select count(*) from empleo.questions),
      'porPlataforma', coalesce((
        select jsonb_object_agg(p.platform, p.total)
        from (select platform, count(*) as total from empleo.jobs group by platform) p
      ), '{}'::jsonb)
    )
    from empleo.jobs j
  );
end $$;

create function public.empleo_vacantes(
  p_busqueda  text    default '',
  p_estado    text    default '',
  p_min_score integer default 0,
  p_limite    integer default 30
) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_limite integer := least(greatest(coalesce(p_limite, 30), 1), 100);
  v_patron text    := '%' || coalesce(p_busqueda, '') || '%';
begin
  perform empleo.exigir_operador();
  return (
    with filtradas as (
      select j.*
      from empleo.jobs j
      where (coalesce(p_busqueda, '') = ''
             or j.title ilike v_patron or j.company_name ilike v_patron or j.location ilike v_patron)
        and (coalesce(p_estado, '') = '' or j.status = p_estado)
        and j.match_score >= coalesce(p_min_score, 0)
    )
    select jsonb_build_object(
      'total', (select count(*) from filtradas),
      'vacantes', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', f.id, 'titulo', f.title, 'empresa', f.company_name,
          'ciudad', coalesce(f.location, ''), 'salario', coalesce(f.salary, 'No especificado'),
          'score', f.match_score, 'estado', f.status, 'plataforma', f.platform,
          'url', f.url, 'actualizada', f.updated_at
        ) order by f.match_score desc, f.updated_at desc)
        from (select * from filtradas order by match_score desc, updated_at desc limit v_limite) f
      ), '[]'::jsonb)
    )
  );
end $$;

-- Serie diaria para la grafica: vacantes vistas por primera vez y postulaciones.
create function public.empleo_actividad(p_dias integer default 30) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_dias integer := least(greatest(coalesce(p_dias, 30), 7), 180);
begin
  perform empleo.exigir_operador();
  return (
    select coalesce(jsonb_agg(jsonb_build_object(
      'dia', d.dia, 'encontradas', d.encontradas, 'postuladas', d.postuladas
    ) order by d.dia), '[]'::jsonb)
    from (
      select dia::date as dia,
        (select count(*) from empleo.jobs j
          where (j.first_seen_at at time zone 'America/Bogota')::date = dia::date) as encontradas,
        (select count(*) from empleo.applications a
          where a.status = 'applied'
            and (a.applied_at at time zone 'America/Bogota')::date = dia::date) as postuladas
      from generate_series(
        (now() at time zone 'America/Bogota')::date - (v_dias - 1),
        (now() at time zone 'America/Bogota')::date,
        interval '1 day'
      ) as dia
    ) d
  );
end $$;

-- ------------------------------------------------------------ panel (boton)

create function public.empleo_estado_agente() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return coalesce((
    select jsonb_build_object(
      'maquina', a.machine,
      'ultimoLatido', a.last_seen_at,
      'navegadorListo', a.browser_ok,
      'enLinea', a.last_seen_at > now() - make_interval(secs => empleo.segundos_agente_en_linea())
    )
    from empleo.agents a order by a.last_seen_at desc limit 1
  ), jsonb_build_object('enLinea', false));
end $$;

create function public.empleo_corridas(p_limite integer default 8) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return coalesce((
    select jsonb_agg(to_jsonb(r) order by r.solicitada desc)
    from (
      select id, max_offers as "maxOfertas", status as estado, machine as maquina,
             requested_at as solicitada, started_at as iniciada, finished_at as terminada,
             exit_code as "codigoSalida", log_tail as log, summary as resumen
      from empleo.bot_runs
      order by requested_at desc
      limit least(greatest(coalesce(p_limite, 8), 1), 50)
    ) r
  ), '[]'::jsonb);
end $$;

-- El clic en "Ejecutar". Una sola corrida viva a la vez: dos bots sobre el
-- mismo Edge se pisan y duplican postulaciones.
create function public.empleo_solicitar_corrida(p_max_ofertas integer) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_id bigint;
begin
  perform empleo.exigir_operador();
  if p_max_ofertas is null or p_max_ofertas not between 1 and 50 then
    raise exception 'El tope debe estar entre 1 y 50 ofertas' using errcode = '22023';
  end if;
  if exists (select 1 from empleo.bot_runs where status in ('pending', 'running')) then
    raise exception 'Ya hay una corrida en cola o en curso' using errcode = '55000';
  end if;
  insert into empleo.bot_runs (requested_by, max_offers)
  values ((select auth.uid()), p_max_ofertas)
  returning id into v_id;
  return jsonb_build_object('id', v_id);
end $$;

create function public.empleo_cancelar_corrida(p_id bigint) returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  update empleo.bot_runs set status = 'cancelled', finished_at = now()
  where id = p_id and status = 'pending';
  if not found then
    raise exception 'Solo se puede cancelar una corrida que no ha empezado' using errcode = '55000';
  end if;
end $$;

-- ------------------------------------------------------------ agente local

create function public.empleo_latido(p_maquina text, p_navegador_listo boolean) returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  insert into empleo.agents (machine, last_seen_at, browser_ok)
  values (p_maquina, now(), p_navegador_listo)
  on conflict (machine) do update set last_seen_at = now(), browser_ok = excluded.browser_ok;
end $$;

-- Al arrancar, el agente cierra lo que dejo a medias si se cayo la PC.
create function public.empleo_reiniciar_agente(p_maquina text) returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  update empleo.bot_runs
  set status = 'failed', finished_at = now(),
      log_tail = coalesce(log_tail, '') || E'\n[agente] Se reinicio el agente antes de terminar.'
  where machine = p_maquina and status = 'running';
end $$;

-- Toma la solicitud pendiente mas antigua. Las viejas caducan: un clic de
-- hace horas no debe disparar postulaciones cuando la PC se prenda.
create function public.empleo_tomar_corrida(p_maquina text) returns jsonb
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_corrida empleo.bot_runs;
begin
  perform empleo.exigir_operador();
  update empleo.bot_runs set status = 'expired', finished_at = now()
  where status = 'pending'
    and requested_at < now() - make_interval(mins => empleo.minutos_vigencia_solicitud());

  update empleo.bot_runs set status = 'running', started_at = now(), machine = p_maquina
  where id = (
    select id from empleo.bot_runs
    where status = 'pending'
    order by requested_at
    limit 1
    for update skip locked
  )
  returning * into v_corrida;

  if v_corrida.id is null then
    return null;
  end if;
  return jsonb_build_object('id', v_corrida.id, 'maxOfertas', v_corrida.max_offers);
end $$;

create function public.empleo_reportar_corrida(
  p_id           bigint,
  p_estado       text,
  p_log          text    default null,
  p_codigo       integer default null,
  p_resumen      jsonb   default null
) returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  if p_estado not in ('running', 'finished', 'failed') then
    raise exception 'Estado de corrida invalido: %', p_estado using errcode = '22023';
  end if;
  update empleo.bot_runs
  set status      = p_estado,
      log_tail    = coalesce(p_log, log_tail),
      exit_code   = coalesce(p_codigo, exit_code),
      summary     = coalesce(p_resumen, summary),
      finished_at = case when p_estado = 'running' then null else now() end
  where id = p_id;
end $$;

-- ------------------------------------------------------------ bot (tracker)

create function public.empleo_urls_vistas(p_estados_finales text[], p_estados_reintento text[],
                                          p_horas_reintento integer) returns setof text
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return query
    select j.url from empleo.jobs j
    where j.status = any (p_estados_finales)
       or (j.status = any (p_estados_reintento)
           and j.updated_at > now() - make_interval(hours => p_horas_reintento));
end $$;

create function public.empleo_urls_con_estado(p_estado text) returns setof text
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return query select j.url from empleo.jobs j where j.status = p_estado;
end $$;

-- Equivale al antiguo record() de MySQL en una sola transaccion: empresa,
-- vacante, habilidades y postulacion. La logica de estados sigue en Python.
create function public.empleo_registrar_oferta(
  p_oferta      jsonb,
  p_habilidades text[] default '{}',
  p_registrar_postulacion boolean default false
) returns bigint
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_empresa    text := coalesce(nullif(p_oferta ->> 'company_name', ''), 'Confidencial');
  v_company_id bigint;
  v_job_id     bigint;
  v_habilidad  text;
  v_skill_id   bigint;
begin
  perform empleo.exigir_operador();

  insert into empleo.companies (name) values (v_empresa)
  on conflict (name) do update set updated_at = now()
  returning id into v_company_id;

  insert into empleo.jobs as j (company_id, platform, title, company_name, salary, location, modality,
                                published_at, url, description, match_score, priority, recommendation, status)
  values (v_company_id, p_oferta ->> 'platform', p_oferta ->> 'title', v_empresa,
          p_oferta ->> 'salary', p_oferta ->> 'location', p_oferta ->> 'modality',
          p_oferta ->> 'published_at', p_oferta ->> 'url', p_oferta ->> 'description',
          coalesce((p_oferta ->> 'match_score')::integer, 0),
          coalesce(p_oferta ->> 'priority', 'normal'),
          p_oferta ->> 'recommendation', p_oferta ->> 'status')
  on conflict (url) do update set
    company_id = excluded.company_id, platform = excluded.platform, title = excluded.title,
    company_name = excluded.company_name, salary = excluded.salary, location = excluded.location,
    published_at = excluded.published_at, description = excluded.description,
    match_score = excluded.match_score, priority = excluded.priority,
    recommendation = excluded.recommendation, status = excluded.status,
    last_seen_at = now(), updated_at = now()
  returning j.id into v_job_id;

  foreach v_habilidad in array coalesce(p_habilidades, '{}') loop
    insert into empleo.skills (name) values (v_habilidad)
    on conflict (name) do update set name = excluded.name
    returning id into v_skill_id;
    insert into empleo.job_skills (job_id, skill_id) values (v_job_id, v_skill_id)
    on conflict do nothing;
  end loop;

  if p_registrar_postulacion then
    insert into empleo.applications (job_id, status, response)
    values (v_job_id, p_oferta ->> 'status', p_oferta ->> 'response')
    on conflict (job_id) do update set
      status = excluded.status, response = excluded.response, updated_at = now();
  end if;

  return v_job_id;
end $$;

create function public.empleo_registrar_pregunta(p_pregunta text, p_respuesta text,
                                                 p_confianza numeric, p_job_id bigint default null)
returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  insert into empleo.questions (question_text, answer_given, confidence_score, job_id)
  values (p_pregunta, p_respuesta, p_confianza, p_job_id);
end $$;

create function public.empleo_patrones_preguntas(p_dias integer default 7, p_limite integer default 20)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return coalesce((
    select jsonb_object_agg(p.patron, jsonb_build_object('count', p.veces, 'avg_confidence', p.confianza))
    from (
      select split_part(q.question_text, '?', 1) as patron, count(*) as veces,
             avg(q.confidence_score)::float as confianza
      from empleo.questions q
      where q.created_at > now() - make_interval(days => p_dias)
      group by 1 order by 2 desc limit p_limite
    ) p
  ), '{}'::jsonb);
end $$;

-- ------------------------------------------------------------ permisos

-- Postgres deja ejecutar funciones a PUBLIC por defecto: se cierra y se abre
-- solo a usuarios con sesion. Igual cada funcion revisa que sea operador.
do $$
declare
  f record;
begin
  for f in
    select p.oid::regprocedure as firma, n.nspname = 'public' as es_api
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where (n.nspname = 'public' and p.proname like 'empleo\_%') or n.nspname = 'empleo'
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.firma);
    if f.es_api then
      execute format('grant execute on function %s to authenticated', f.firma);
    end if;
  end loop;
end $$;
