-- Fase 2: seguimiento de postulaciones por correo.
-- Cada correo relevante (test, entrevista, contacto, avance, rechazo) es un
-- evento. Se asocia a la vacante postulada cuando el asunto la nombra.

create table empleo.application_events (
  id          bigint generated by default as identity primary key,
  message_id  text not null unique,              -- Message-ID del correo: evita duplicados
  job_id      bigint references empleo.jobs (id) on delete set null,
  categoria   text not null check (categoria in
                ('accion_requerida', 'contacto_humano', 'avance', 'rechazo')),
  motivo      text,
  remitente   text not null,
  asunto      text not null,
  cargo       text,                               -- cargo leido del asunto
  enlace      text,                               -- enlace a la prueba o mensaje
  recibido_at timestamptz not null,
  atendido    boolean not null default false,
  created_at  timestamptz not null default now()
);
create index application_events_job_idx on empleo.application_events (job_id);
create index application_events_pendientes_idx on empleo.application_events (atendido, recibido_at desc);
alter table empleo.application_events enable row level security;

-- Registra un evento y lo asocia a la vacante postulada mas reciente cuyo
-- titulo coincide con el cargo del asunto. Devuelve true si era nuevo.
create function public.empleo_registrar_evento(p_evento jsonb) returns boolean
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_cargo  text := nullif(trim(p_evento ->> 'cargo'), '');
  v_job_id bigint;
begin
  perform empleo.exigir_operador();
  if v_cargo is not null then
    select j.id into v_job_id from empleo.jobs j
    where j.status = 'applied'
      and (lower(j.title) = lower(v_cargo) or j.title ilike '%' || v_cargo || '%'
           or v_cargo ilike '%' || j.title || '%')
    order by j.updated_at desc limit 1;
  end if;

  insert into empleo.application_events
    (message_id, job_id, categoria, motivo, remitente, asunto, cargo, enlace, recibido_at)
  values (p_evento ->> 'message_id', v_job_id, p_evento ->> 'categoria', p_evento ->> 'motivo',
          p_evento ->> 'remitente', p_evento ->> 'asunto', v_cargo, p_evento ->> 'enlace',
          (p_evento ->> 'recibido_at')::timestamptz)
  on conflict (message_id) do nothing;
  return found;
end $$;

create function public.empleo_eventos(p_limite integer default 30, p_solo_pendientes boolean default false)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return coalesce((
    select jsonb_agg(to_jsonb(e) order by e.recibido desc)
    from (
      select ev.id, ev.categoria, ev.motivo, ev.remitente, ev.asunto, ev.cargo, ev.enlace,
             ev.recibido_at as recibido, ev.atendido,
             j.title as vacante, j.company_name as empresa, j.platform as plataforma, j.url
      from empleo.application_events ev
      left join empleo.jobs j on j.id = ev.job_id
      where not p_solo_pendientes
         or (not ev.atendido and ev.categoria in ('accion_requerida', 'contacto_humano'))
      order by ev.recibido_at desc
      limit least(greatest(coalesce(p_limite, 30), 1), 200)
    ) e
  ), '[]'::jsonb);
end $$;

create function public.empleo_marcar_evento_atendido(p_id bigint, p_atendido boolean default true)
returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  update empleo.application_events set atendido = p_atendido where id = p_id;
end $$;

-- Embudo para el panel: cuantas postulaciones llegaron a cada etapa.
create function public.empleo_embudo() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  perform empleo.exigir_operador();
  return jsonb_build_object(
    'postuladas', (select count(*) from empleo.applications where status = 'applied'),
    'conRespuesta', (select count(distinct coalesce(job_id::text, message_id)) from empleo.application_events),
    'accionRequerida', (select count(*) from empleo.application_events where categoria = 'accion_requerida'),
    'contactos', (select count(*) from empleo.application_events where categoria = 'contacto_humano'),
    'rechazos', (select count(*) from empleo.application_events where categoria = 'rechazo'),
    'pendientes', (select count(*) from empleo.application_events
                   where not atendido and categoria in ('accion_requerida', 'contacto_humano'))
  );
end $$;

revoke all on function public.empleo_registrar_evento(jsonb) from public, anon;
revoke all on function public.empleo_eventos(integer, boolean) from public, anon;
revoke all on function public.empleo_marcar_evento_atendido(bigint, boolean) from public, anon;
revoke all on function public.empleo_embudo() from public, anon;
grant execute on function public.empleo_registrar_evento(jsonb) to authenticated;
grant execute on function public.empleo_eventos(integer, boolean) to authenticated;
grant execute on function public.empleo_marcar_evento_atendido(bigint, boolean) to authenticated;
grant execute on function public.empleo_embudo() to authenticated;
